### ISSUE TITLE
incorrect-fsf-address

### ISSUE THREAD

**Issue by raveit65** [mate-desktop-legacy-archive/mate-vfs#3]
[rave@mother ~]$ rpmlint /var/lib/mock/fedora-16-x86_64/mate-vfs-1.4.0-5.fc16.x86_64.rpm 
mate-vfs.x86_64: W: spelling-error %description -l en_US http -> HTTP
mate-vfs.x86_64: W: spelling-error %description -l en_US backend -> backed, back end, back-end
mate-vfs.x86_64: W: conffile-without-noreplace-flag /etc/mate-vfs-2.0/modules/cdda-module.conf
mate-vfs.x86_64: W: conffile-without-noreplace-flag /etc/mate-vfs-2.0/modules/default-modules.conf
mate-vfs.x86_64: W: conffile-without-noreplace-flag /etc/mate-vfs-2.0/modules/ssl-modules.conf
mate-vfs.x86_64: E: incorrect-fsf-address /usr/share/doc/mate-vfs-1.4.0/COPYING
mate-vfs.x86_64: W: non-conffile-in-etc /etc/mateconf/schemas/desktop_mate_url_handlers.schemas
mate-vfs.x86_64: W: file-not-utf8 /usr/share/doc/mate-vfs-1.4.0/AUTHORS
mate-vfs.x86_64: W: non-conffile-in-etc /etc/mateconf/schemas/system_smb.schemas
mate-vfs.x86_64: E: incorrect-fsf-address /usr/share/doc/mate-vfs-1.4.0/COPYING.LIB
mate-vfs.x86_64: W: non-conffile-in-etc /etc/mateconf/schemas/system_http_proxy.schemas
mate-vfs.x86_64: W: non-conffile-in-etc /etc/mateconf/schemas/desktop_default_applications.schemas
mate-vfs.x86_64: W: non-conffile-in-etc /etc/mateconf/schemas/system_dns_sd.schemas
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-monitor
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-ls
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-copy
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-rm
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-mv
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-mkdir
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-cat
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-info
mate-vfs.x86_64: W: no-manual-page-for-binary matevfs-df
1 packages and 0 specfiles checked; 2 errors, 20 warnings.

[rave@mother ~]$ rpmlint /var/lib/mock/fedora-16-x86_64/mate-vfs-devel-1.4.0-5.fc16.x86_64.rpm 
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-ops.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-mime-handlers.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-mime-deprecated.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-mime-utils.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-file-info.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-module-shared.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-xfer.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-utils.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-volume-monitor.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-uri.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-drive.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-types.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-module.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-mime.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-application-registry.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-socket-buffer.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-address.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-module-callback.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-monitor.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/lib64/mate-vfs-2.0/include/mate-vfs-file-size.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-init.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-directory.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-acl.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-dns-sd.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-mime-info.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-pty.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-handle.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-ace.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-cancellable-ops.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-result.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-async-ops.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-parse-ls.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-cancellation.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-ssl.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-resolve.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-volume.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-transform.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-standard-callbacks.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-version.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-method.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-file-size.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-mime-monitor.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-context.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-inet-connection.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-job-limit.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-mime-info-cache.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-socket.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs-find-directory.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-module-2.0/libmatevfs/mate-vfs-module-callback-module-api.h
mate-vfs-devel.x86_64: E: incorrect-fsf-address /usr/include/mate-vfs-2.0/libmatevfs/mate-vfs.h
1 packages and 0 specfiles checked; 50 errors, 0 warnings.

At this point i'm giving up.
We need a script for do the work ;)

**Comment by ghost** [comment]
Wolfgang, I agree; If this isn't really a blocker for Fedora tell people it will be fixed in the next release. Otherwise I'll give it a go on the weekend, ok ?

**Comment by raveit65** [comment]
Hi Nelson,
no need to get stress
http://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address
I only have to inform the upstream if i find such a error.
That's all.
