### ISSUE TITLE
do mate really need this?

### ISSUE THREAD

**Issue by raveit65** [mate-desktop-legacy-archive/mate-vfs#4]
In the mate-vfs package of my repo in used some patches which i've ported from fc14 (last gnome-2.3x) release from fedora.
For my package review request i think about to use them or not.
https://bugzilla.redhat.com/show_bug.cgi?id=844164
Are this patches useful, a 'nice to have', total nonsense, or push they fedora mate version far from  original mate?
So if anyone could make some concerns this would be helpful for me.

Patch0:     gnome-vfs-2.9.90-modules-conf.patch
https://dl.dropbox.com/u/49862637/Mate-desktop/mate-vfs/gnome-vfs-2.9.90-modules-conf.patch

Patch1: gnome-vfs-2.8.2-browser_default.patch
https://dl.dropbox.com/u/49862637/Mate-desktop/mate-vfs/gnome-vfs-2.8.2-browser_default.patch
I think this one is clear, no one wants epiphany in mate.

https://bugzilla.redhat.com/show_bug.cgi?id=197868
Patch2:     gnome-vfs-2.15.91-mailto-command.patch
https://dl.dropbox.com/u/49862637/Mate-desktop/mate-vfs/gnome-vfs-2.15.91-mailto-command.patch
Ok, mate don't use evolution, but it is in the code.

https://bugzilla.redhat.com/show_bug.cgi?id=333041
https://bugzilla.redhat.com/show_bug.cgi?id=335241
Patch3: gnome-vfs-2.20.0-ignore-certain-mountpoints.patch
https://dl.dropbox.com/u/49862637/Mate-desktop/mate-vfs/gnome-vfs-2.20.0-ignore-certain-mountpoints.patch

gnome-vfs-daemon exits on dbus, and constantly restarted causing dbus/hal to hog CPU
https://bugzilla.redhat.com/show_bug.cgi?id=486286
Patch4: gnome-vfs-2.24.xx-utf8-mounts.patch
https://dl.dropbox.com/u/49862637/Mate-desktop/mate-vfs/gnome-vfs-2.24.xx-utf8-mounts.patch

Thank you

**Comment by stefano-k** [comment]
http://wiki.mate-desktop.org/matevfs_to_gio

**Comment by raveit65** [comment]
Stefano, i'm only a little packager dummy.
Can you explain more detailed what you mean, and which patches this effects?
Thank you

**Comment by stefano-k** [comment]
we'll drop mate-vfs package and use gio/gvfs instead, so I think atm we dont need these patches

**Comment by raveit65** [comment]
Ahh, that means if all packages which have mate-vfs dep are updated, you remove mate-vfs from uptream.
I notice today that mate-system-monitor 1.4.0 don't need mate-vfs anymore as dep.
Which packages are not updated currently? 
-.... doesn't matter, i will see it.

**Comment by stefano-k** [comment]
mate-vfs is removed
