### ISSUE TITLE
gvfs-open URL  opens firefox at a blank page  (also breaks ubuntu-bug)

### ISSUE THREAD

**Issue by RichardNeill** [mate-desktop-legacy-archive/mate-vfs#6]
Invoking   gvfs-open http://example.com   is supposed to open a new browser window/tab at http://example.com.  Instead, it opens a new browser tab at a the user's start-page.

This causes all sorts of breakage, particularly with ubuntu-bug. Here's my original report:
https://bugs.launchpad.net/ubuntu/+source/apport/+bug/1464053

Sorry if I'm filing this in the wrong place - I had to guess, and I'm not sure what the correct way is for me to have determined which of the mate-desktop projects contains the gvfs-open binary.

**Comment by infirit** [comment]
mate-vfs was a fork of gvfs and is no more. You should file this bug with the gvfs folks at bugzilla.gnome.org

**Comment by RichardNeill** [comment]
Thanks for your comment. If gvfs is no more, then the real problem lies in the xdg-open script, which still uses it explicitly within Mate. I quote the relevant section:

open_mate(){
    if gvfs-open --help 2>/dev/null 1>&2; then
        gvfs-open "$1"
    else
        mate-open "$1"
    fi
.....
}

Can you tell me, for Mate, what command should the /usr/bin/xdg-open program be calling, instead of gvfs-open?
[Note that mate-open doesn't exist on Ubuntu]. I'll get then try to get this fixed in the right place.

Thanks - Richard

**Comment by infirit** [comment]
> If gvfs is no more

I did not say that, I said **mate**-vfs is no more, gvfs is very much alive but not maintained by MATE :wink:.

mate-vfs was a fork of gvfs and used when MATE started out. But mate-vfs has long been obsoleted and we use gvfs now.

The xdg-open script still has mate-open as it aims to work across all desktops.

**Comment by RichardNeill** [comment]
Thanks. Sorry, I misunderstood that - my (incorrect) assumption was that the mate-vfs project's fork of the gvfs-open binary was the surviving fork (after Gnome2 was EOLd), and that now even mate-vfs had moved to something else. Now I know, I'll re-file this bug under gvfs-open at the gnome bugzilla as you suggest. Thanks.

**Comment by RichardNeill** [comment]
I just did an experiment.
- In the Mate environment, running "gvfs-open http://www.bbc.co.uk"  opens a blank firefox window.
- In the Gnome (Unity) environment, running the same command opens the BBC webpage.

So, this is going to be a fun bug to assign: I expect that the gnome folks will (reasonably enough) say that this is Mate's issue. Can you tell me what I should do? Thanks.

**Comment by infirit** [comment]
`gvfs-open http://www.bbc.co.uk` works fine for me here on gentoo with MATE. I suggest you leave this with the distro who can better figure out what is the problem and file a bug upstream (here or at gnome).

**Comment by RichardNeill** [comment]
Thanks. That sounds like the root-cause problem is something that Ubuntu have done with Ubuntu-Mate, and therefore I'll file it there. Thank you for your help in tracking this down.
